# Generated by Django 3.2.13 on 2023-08-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderIterm',
            new_name='OrderItem',
        ),
    ]
